### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aidooyaw1992** [Sach97/rusty_ffi.dart#1]
var play_once =
      dl.lookupFunction<NativeRustPlayOnceFunction, NativeRustPlayOnceFunction>(
          "play_once");

i keep getting an underlined error at the NativeRustPlayOnceFunction. i dont understand why

The type 'Void Function(Pointer<Utf8>)' must be a subtype of 'Void Function(Pointer<Utf8>)' for 'lookupFunction'.
Try changing one or both of the type arguments.

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
# path: ^1.6.0
ffi: ^0.1.3
dev_dependencies:
  
  pedantic: ^1.8.0
  test: ^1.6.0

**Comment by sachaarbonel** [comment]
Hmm the dart 2.6 release and ffi utilities package broke some of my builds on other projects too I'll push the changes

**Comment by sachaarbonel** [comment]
@aidooyaw1992 I pushed a fix let me know if it works for you

**Comment by aidooyaw1992** [comment]
this is the error i got again

Unhandled exception:
Invalid argument(s): Failed to load dynamic library (126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:19:12)
#2      main (file:///C:/Users/Aidoo/Documents/rust_projects/rusty_ffi/bin/main.dart:18:49)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by sachaarbonel** [comment]
Sorry it seems that you are on windows and I didn't handled the windows case my bad I'll push an other fix asap

**Comment by sachaarbonel** [comment]
@aidooyaw1992 it should work with my latest commit #7d8f7c3

**Comment by aidooyaw1992** [comment]
ok im gonna try it now

**Comment by aidooyaw1992** [comment]
ok well, when i tried it by changing it to this:  

dylib = ffi.DynamicLibrary.open("target/debug/play_once.dll");

and it worked but i didnt get anything

**Comment by sachaarbonel** [comment]
Does the rodio examples work for you : https://github.com/RustAudio/rodio?

**Comment by aidooyaw1992** [comment]
it just runs but i dont get any output to play. Please whats it supposed to happen actuallly

**Comment by aidooyaw1992** [comment]
im checking the github repo u sent

**Comment by sachaarbonel** [comment]
Ok I think I found the issue, on mac and windows you need to set_volume (rust side). I just pushed a fix check it out

**Comment by aidooyaw1992** [comment]
ok i will check it out soon. Thanks for your quick response, you are amazing

**Comment by aidooyaw1992** [comment]
hi it worked like a charm, thanks. My first of running successful rustproject

**Comment by sachaarbonel** [comment]
Congrats mate, this is the first of many!
