### ISSUE TITLE
signing needed on macos

### ISSUE THREAD

**Issue by modulovalue** [Sach97/rusty_ffi.dart#2]
Thank you for the tutorial.
I ran into an issue where the dart binary needs to be signed on macOS for the rust lib to be used.

For anyone running into the same issue check out https://github.com/dart-lang/sdk/issues/38314

(TLDR: run `codesign --remove-signature DARTPATH/bin/dart`)

**Comment by sachaarbonel** [comment]
By "dart binary" you mean you tried dart2native on this? Because running dart bin/main.dart works on my Mac

**Comment by sachaarbonel** [comment]
Also I need to update the article which is now outdated

**Comment by modulovalue** [comment]
Sorry for the late response
By dart binary I meant the dart file that gets executed when any dart command gets called (dart main.dart) the one under ....bin/dart. It did work for me only after I ran the command on it but I’m not sure why you don’t need to. Maybe it’s Catalina, are you on catalina?

I’ve also tried to use your tutorial on Desktop but the dylib only works for me if I remove the sandbox entitlements from the macOS Xcode project and also use a global path to the .dylib, I’m planning to investigate that issue further soon, but I’d be curious if dylibs are working fine for you on your machine when used in a Flutter macOS project.

**Comment by sachaarbonel** [comment]
Really weird @modulovalue  , I am on MacOSx Catalina too :  
```
Flutter (Channel master, v1.12.3-pre.43, on Mac OS X 10.14.6 18G1012, locale
    fr-US)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
```
It might be a problem related to your rust's DYLD_LIBRARY_PATH, try this SO [response](https://stackoverflow.com/questions/55282165/dylib-cannot-load-libstd-when-compiled-in-a-workspace)

**Comment by modulovalue** [comment]
```
[✓] Flutter (Channel unknown, v1.12.3-pre.35, on Mac OS X 10.15.1 19B88, locale de-DE)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
```
> try this SO response

Will do, thanks!
